# Generated by Django 3.0.3 on 2020-08-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tag',
            field=models.CharField(default='', max_length=100),
        ),
    ]
